#!/bin/bash

#PBS -N nad4L
#PBS -q tiny12core
#PBS -j oe
#PBS -m abe
#PBS -M jamolina@uark.edu
#PBS -o molina_pineda_assn04.1.out
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:00:30:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+

cd /storage/jamolina/watermelon_files/watermelon_nt 
makeblastdb -in nad4L.fasta -dbtype nucl -out nad4Ldb.fasta
blastn -query nad4L.fasta -db nad4Ldb.fasta 
