#!/bin/bash

#PBS -N nad4L
#PBS -q tiny12core
#PBS -j oe
#PBS -m abe
#PBS -M jamolina@uark.edu
#PBS -o molina_pineda_assn04.3.out
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:00:30:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+

cd /storage/jamolina/watermelon_files/
makeblastdb -in watermelon.fsa -dbtype nucl 
blastn -query /storage/jamolina/watermelon_files/watermelon_nt/nad4L.fasta -db watermelon.fsa 
